const BUILT_IN_WEBSITE_TEMPLATES = [
  {
    name: 'Free Simple',
    slug: 'free-simple',
    preview_image: '',
    template_code_key: 'free_simple',
    description: 'Simple free website storefront template.',
    is_premium: 0,
    status: 'active',
  },
  {
    name: 'Premium Brand',
    slug: 'premium-brand',
    preview_image: '',
    template_code_key: 'premium_brand',
    description: 'Premium visual storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Mega Electronics',
    slug: 'mega-electronics',
    preview_image: '',
    template_code_key: 'mega_electronics',
    description: 'Electronics premium storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Supplement Theme',
    slug: 'supplement-theme',
    preview_image: '',
    template_code_key: 'supplement_theme',
    description: 'Supplement and nutrition storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Furniture Theme',
    slug: 'furniture-theme',
    preview_image: '',
    template_code_key: 'furniture_theme',
    description: 'Furniture storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Grocery Theme',
    slug: 'grocery-theme',
    preview_image: '',
    template_code_key: 'grocery_theme',
    description: 'Grocery storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Multi Product',
    slug: 'multi-product',
    preview_image: '',
    template_code_key: 'multi_product',
    description: 'Multi product premium storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Mextro',
    slug: 'mextro',
    preview_image: '',
    template_code_key: 'mextro',
    description: 'Electro-style premium storefront template.',
    is_premium: 1,
    status: 'active',
  },
  {
    name: 'Xxam',
    slug: 'xxam',
    preview_image: '',
    template_code_key: 'xxam',
    description: 'Minimal electronics premium storefront template.',
    is_premium: 1,
    status: 'active',
  },
];

module.exports = {
  BUILT_IN_WEBSITE_TEMPLATES,
};