CREATE TABLE IF NOT EXISTS webinar_cloudfront_log_objects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_bucket VARCHAR(255) NOT NULL,
  source_key VARCHAR(1024) NOT NULL,
  source_key_hash CHAR(64) NOT NULL,
  source_etag VARCHAR(255) NULL,
  source_size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_last_modified DATETIME NULL,
  status ENUM('processing','processed','failed') NOT NULL DEFAULT 'processing',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  records_total BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_sc_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  hls_records BIGINT UNSIGNED NOT NULL DEFAULT 0,
  hls_sc_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  attributed_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unattributed_hls_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  processed_at DATETIME NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_webinar_cloudfront_log_key_hash (source_key_hash),
  KEY idx_webinar_cloudfront_log_status_updated (status, updated_at),
  KEY idx_webinar_cloudfront_log_last_modified (source_last_modified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;