function makeLepresiumWords(count) {
  return Array.from({ length: count }, () => 'Lepresium').join(' ');
}

function makeLepresiumSentence(minWords, maxWords) {
  const target = minWords === maxWords ? minWords : maxWords;
  return makeLepresiumWords(target);
}

function makeLepresiumUrl() {
  return 'https://supgad.com/lepresium';
}

function buildField({
  field_key,
  field_type = 'text',
  label,
  section,
  helper_text = '',
  required = true,
  word_rule = null,
  default_value = '',
  placeholder = '',
  sort_order,
}) {
  return {
    field_key,
    field_type,
    field_value: default_value,
    sort_order,
    meta: {
      label,
      section,
      helper_text,
      required,
      word_rule,
      placeholder,
      locked: true,
    },
  };
}

function buildButton({
  button_key,
  button_label,
  button_style = 'primary',
  label,
  helper_text = '',
  required = true,
  sort_order,
}) {
  return {
    button_key,
    button_label,
    button_url: makeLepresiumUrl(),
    button_style,
    open_in_new_tab: true,
    sort_order,
    meta: {
      label,
      helper_text,
      required,
      locked: true,
    },
  };
}

export default function createDxtTemplatePreset() {
  const fields = [
    buildField({
      field_key: 'top_bar_title',
      field_type: 'text',
      label: 'Top bar title',
      section: 'Top bar',
      helper_text: 'Slim green announcement line.',
      word_rule: { mode: 'range', min_words: 8, max_words: 14, label: 'Top bar title' },
      default_value: makeLepresiumSentence(12, 12),
      placeholder: 'Enter at least 8 words',
      sort_order: 1,
    }),
    buildField({
      field_key: 'hero_product_image',
      field_type: 'image',
      label: 'Hero product image',
      section: 'Hero',
      helper_text: 'Main bottle or pack image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 2,
    }),
    buildField({
      field_key: 'hero_title',
      field_type: 'text',
      label: 'Hero title',
      section: 'Hero',
      helper_text: 'Main sales headline.',
      word_rule: { mode: 'range', min_words: 10, max_words: 18, label: 'Hero title' },
      default_value: makeLepresiumSentence(14, 14),
      placeholder: 'Enter at least 10 words',
      sort_order: 3,
    }),
    buildField({
      field_key: 'hero_intro_paragraph_1',
      field_type: 'textarea',
      label: 'Hero intro paragraph 1',
      section: 'Hero',
      helper_text: 'Opening sales paragraph.',
      word_rule: { mode: 'range', min_words: 24, max_words: 40, label: 'Hero intro paragraph 1' },
      default_value: makeLepresiumSentence(36, 36),
      placeholder: 'Enter at least 24 words',
      sort_order: 4,
    }),
    buildField({
      field_key: 'hero_intro_paragraph_2',
      field_type: 'textarea',
      label: 'Hero intro paragraph 2',
      section: 'Hero',
      helper_text: 'Second supporting paragraph.',
      word_rule: { mode: 'range', min_words: 24, max_words: 40, label: 'Hero intro paragraph 2' },
      default_value: makeLepresiumSentence(36, 36),
      placeholder: 'Enter at least 24 words',
      sort_order: 5,
    }),
    buildField({
      field_key: 'hero_small_cta_line',
      field_type: 'text',
      label: 'Hero small CTA line',
      section: 'Hero',
      helper_text: 'Small promise line above buttons.',
      word_rule: { mode: 'range', min_words: 4, max_words: 9, label: 'Hero small CTA line' },
      default_value: makeLepresiumSentence(6, 6),
      placeholder: 'Enter at least 4 words',
      sort_order: 6,
    }),
    buildField({
      field_key: 'hero_trust_item_1',
      field_type: 'text',
      label: 'Hero trust item 1',
      section: 'Hero',
      helper_text: 'First trust bullet.',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Hero trust item 1' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter at least 2 words',
      sort_order: 7,
    }),
    buildField({
      field_key: 'hero_trust_item_2',
      field_type: 'text',
      label: 'Hero trust item 2',
      section: 'Hero',
      helper_text: 'Second trust bullet.',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Hero trust item 2' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter at least 2 words',
      sort_order: 8,
    }),
    buildField({
      field_key: 'hero_trust_item_3',
      field_type: 'text',
      label: 'Hero trust item 3',
      section: 'Hero',
      helper_text: 'Third trust bullet.',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Hero trust item 3' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter at least 2 words',
      sort_order: 9,
    }),
    buildField({
      field_key: 'hero_review_text',
      field_type: 'text',
      label: 'Hero review text',
      section: 'Hero',
      helper_text: 'Review/support line below stars.',
      word_rule: { mode: 'range', min_words: 2, max_words: 6, label: 'Hero review text' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 10,
    }),

    buildField({
      field_key: 'hero_badge_logo_1',
      field_type: 'image',
      label: 'Hero badge logo 1',
      section: 'Hero',
      helper_text: 'First circular badge/logo under the review line.',
      default_value: '',
      placeholder: 'Upload logo image or paste image URL',
      sort_order: 11,
    }),
    buildField({
      field_key: 'hero_badge_logo_2',
      field_type: 'image',
      label: 'Hero badge logo 2',
      section: 'Hero',
      helper_text: 'Second circular badge/logo under the review line.',
      default_value: '',
      placeholder: 'Upload logo image or paste image URL',
      sort_order: 12,
    }),
    buildField({
      field_key: 'hero_badge_logo_3',
      field_type: 'image',
      label: 'Hero badge logo 3',
      section: 'Hero',
      helper_text: 'Third circular badge/logo under the review line.',
      default_value: '',
      placeholder: 'Upload logo image or paste image URL',
      sort_order: 13,
    }),
    buildField({
      field_key: 'hero_badge_logo_4',
      field_type: 'image',
      label: 'Hero badge logo 4',
      section: 'Hero',
      helper_text: 'Fourth circular badge/logo under the review line.',
      default_value: '',
      placeholder: 'Upload logo image or paste image URL',
      sort_order: 14,
    }),
    buildField({
      field_key: 'hero_badge_logo_5',
      field_type: 'image',
      label: 'Hero badge logo 5',
      section: 'Hero',
      helper_text: 'Fifth circular badge/logo under the review line.',
      default_value: '',
      placeholder: 'Upload logo image or paste image URL',
      sort_order: 15,
    }),

    buildField({
      field_key: 'how_this_product_works_title',
      field_type: 'text',
      label: 'How this product works title',
      section: 'How this product works',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 4, max_words: 7, label: 'How this product works title' },
      default_value: 'How This Product Works',
      placeholder: 'Enter at least 4 words',
      sort_order: 16,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_1',
      field_type: 'textarea',
      label: 'How this product works paragraph 1',
      section: 'How this product works',
      helper_text: 'First explanatory paragraph.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'How this product works paragraph 1' },
      default_value: makeLepresiumSentence(28, 28),
      placeholder: 'Enter at least 18 words',
      sort_order: 17,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_2',
      field_type: 'textarea',
      label: 'How this product works paragraph 2',
      section: 'How this product works',
      helper_text: 'Second explanatory paragraph.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'How this product works paragraph 2' },
      default_value: makeLepresiumSentence(28, 28),
      placeholder: 'Enter at least 18 words',
      sort_order: 18,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_3',
      field_type: 'textarea',
      label: 'How this product works paragraph 3',
      section: 'How this product works',
      helper_text: 'Third explanatory paragraph.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'How this product works paragraph 3' },
      default_value: makeLepresiumSentence(28, 28),
      placeholder: 'Enter at least 18 words',
      sort_order: 19,
    }),
    buildField({
      field_key: 'how_this_product_works_image',
      field_type: 'image',
      label: 'How this product works image',
      section: 'How this product works',
      helper_text: 'Supporting section image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 20,
    }),

    buildField({
      field_key: 'ingredients_section_title',
      field_type: 'text',
      label: 'Ingredients section title',
      section: 'Ingredients',
      helper_text: 'Ingredients section title.',
      word_rule: { mode: 'range', min_words: 1, max_words: 4, label: 'Ingredients section title' },
      default_value: 'Ingredients',
      placeholder: 'Enter title',
      sort_order: 21,
    }),
    buildField({
      field_key: 'ingredients_intro',
      field_type: 'textarea',
      label: 'Ingredients intro',
      section: 'Ingredients',
      helper_text: 'Intro to ingredients.',
      word_rule: { mode: 'range', min_words: 12, max_words: 24, label: 'Ingredients intro' },
      default_value: makeLepresiumSentence(20, 20),
      placeholder: 'Enter at least 12 words',
      sort_order: 22,
    }),
    ...Array.from({ length: 5 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `ingredient_${i}_title`,
          field_type: 'text',
          label: `Ingredient ${i} title`,
          section: 'Ingredients',
          helper_text: 'Ingredient title.',
          word_rule: { mode: 'range', min_words: 1, max_words: 4, label: `Ingredient ${i} title` },
          default_value: makeLepresiumSentence(2, 2),
          placeholder: 'Enter ingredient title',
          sort_order: 22 + i * 2 - 1,
        }),
        buildField({
          field_key: `ingredient_${i}_text`,
          field_type: 'textarea',
          label: `Ingredient ${i} text`,
          section: 'Ingredients',
          helper_text: 'Ingredient description.',
          word_rule: { mode: 'range', min_words: 10, max_words: 22, label: `Ingredient ${i} text` },
          default_value: makeLepresiumSentence(18, 18),
          placeholder: 'Enter at least 10 words',
          sort_order: 22 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'ingredients_closing_line',
      field_type: 'textarea',
      label: 'Ingredients closing line',
      section: 'Ingredients',
      helper_text: 'Ingredients closing line.',
      word_rule: { mode: 'range', min_words: 12, max_words: 24, label: 'Ingredients closing line' },
      default_value: makeLepresiumSentence(18, 18),
      placeholder: 'Enter at least 12 words',
      sort_order: 33,
    }),
    buildField({
      field_key: 'ingredients_image',
      field_type: 'image',
      label: 'Ingredients image',
      section: 'Ingredients',
      helper_text: 'Ingredients image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 34,
    }),

    buildField({
      field_key: 'benefits_title',
      field_type: 'text',
      label: 'Benefits title',
      section: 'Benefits',
      helper_text: 'Benefits section title.',
      word_rule: { mode: 'range', min_words: 1, max_words: 4, label: 'Benefits title' },
      default_value: 'Benefits',
      placeholder: 'Enter title',
      sort_order: 35,
    }),
    buildField({
      field_key: 'benefits_intro',
      field_type: 'textarea',
      label: 'Benefits intro',
      section: 'Benefits',
      helper_text: 'Benefits intro paragraph.',
      word_rule: { mode: 'range', min_words: 12, max_words: 24, label: 'Benefits intro' },
      default_value: makeLepresiumSentence(18, 18),
      placeholder: 'Enter at least 12 words',
      sort_order: 36,
    }),
    ...Array.from({ length: 6 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `benefit_${i}_title`,
          field_type: 'text',
          label: `Benefit ${i} title`,
          section: 'Benefits',
          helper_text: 'Benefit title.',
          word_rule: { mode: 'range', min_words: 2, max_words: 6, label: `Benefit ${i} title` },
          default_value: makeLepresiumSentence(4, 4),
          placeholder: 'Enter at least 2 words',
          sort_order: 36 + i * 2 - 1,
        }),
        buildField({
          field_key: `benefit_${i}_text`,
          field_type: 'textarea',
          label: `Benefit ${i} text`,
          section: 'Benefits',
          helper_text: 'Benefit description.',
          word_rule: { mode: 'range', min_words: 10, max_words: 22, label: `Benefit ${i} text` },
          default_value: makeLepresiumSentence(18, 18),
          placeholder: 'Enter at least 10 words',
          sort_order: 36 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'benefits_closing_line',
      field_type: 'textarea',
      label: 'Benefits closing line',
      section: 'Benefits',
      helper_text: 'Benefits closing line.',
      word_rule: { mode: 'range', min_words: 12, max_words: 24, label: 'Benefits closing line' },
      default_value: makeLepresiumSentence(18, 18),
      placeholder: 'Enter at least 12 words',
      sort_order: 49,
    }),

    buildField({
      field_key: 'testimonials_title',
      field_type: 'text',
      label: 'Testimonials title',
      section: 'Testimonials',
      helper_text: 'Testimonials section title.',
      word_rule: { mode: 'range', min_words: 3, max_words: 6, label: 'Testimonials title' },
      default_value: 'What Users Are Saying',
      placeholder: 'Enter at least 3 words',
      sort_order: 50,
    }),
    ...Array.from({ length: 3 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `testimonial_${i}_image`,
          field_type: 'image',
          label: `Testimonial ${i} image`,
          section: 'Testimonials',
          helper_text: 'Reviewer image.',
          default_value: '',
          placeholder: 'Upload image or paste image URL',
          sort_order: 50 + i * 3 - 2,
        }),
        buildField({
          field_key: `testimonial_${i}_name_line`,
          field_type: 'text',
          label: `Testimonial ${i} name line`,
          section: 'Testimonials',
          helper_text: 'Reviewer name line.',
          word_rule: { mode: 'range', min_words: 2, max_words: 6, label: `Testimonial ${i} name line` },
          default_value: makeLepresiumSentence(4, 4),
          placeholder: 'Enter at least 2 words',
          sort_order: 50 + i * 3 - 1,
        }),
        buildField({
          field_key: `testimonial_${i}_text`,
          field_type: 'textarea',
          label: `Testimonial ${i} text`,
          section: 'Testimonials',
          helper_text: 'Reviewer text.',
          word_rule: { mode: 'range', min_words: 18, max_words: 36, label: `Testimonial ${i} text` },
          default_value: makeLepresiumSentence(30, 30),
          placeholder: 'Enter at least 18 words',
          sort_order: 50 + i * 3,
        }),
      ];
    }).flat(),

    buildField({
      field_key: 'pricing_title',
      field_type: 'text',
      label: 'Pricing title',
      section: 'Pricing',
      helper_text: 'Pricing section title.',
      word_rule: { mode: 'range', min_words: 4, max_words: 8, label: 'Pricing title' },
      default_value: makeLepresiumSentence(6, 6),
      placeholder: 'Enter at least 4 words',
      sort_order: 60,
    }),

    buildField({
      field_key: 'pricing_card_1_package_title',
      field_type: 'text',
      label: 'Pricing card 1 package title',
      section: 'Pricing',
      helper_text: 'Example: 1 X BOTTLE',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 1 package title' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter package title',
      sort_order: 61,
    }),
    buildField({
      field_key: 'pricing_card_1_supply_label',
      field_type: 'text',
      label: 'Pricing card 1 supply label',
      section: 'Pricing',
      helper_text: 'Example: 30 day Supply',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 1 supply label' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter supply label',
      sort_order: 62,
    }),
    buildField({
      field_key: 'pricing_card_1_image',
      field_type: 'image',
      label: 'Pricing card 1 image',
      section: 'Pricing',
      helper_text: 'Large pricing product image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 63,
    }),
    buildField({
      field_key: 'pricing_card_1_price_text',
      field_type: 'text',
      label: 'Pricing card 1 main price',
      section: 'Pricing',
      helper_text: 'Example: $69',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 1 main price' },
      default_value: '$69',
      placeholder: 'Enter main price',
      sort_order: 64,
    }),
    buildField({
      field_key: 'pricing_card_1_price_suffix',
      field_type: 'text',
      label: 'Pricing card 1 price suffix',
      section: 'Pricing',
      helper_text: 'Example: /Bottle',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 1 price suffix' },
      default_value: '/Bottle',
      placeholder: 'Enter price suffix',
      sort_order: 65,
    }),
    buildField({
      field_key: 'pricing_card_1_total_label',
      field_type: 'text',
      label: 'Pricing card 1 total label',
      section: 'Pricing',
      helper_text: 'Example: TOTAL:',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 1 total label' },
      default_value: 'TOTAL:',
      placeholder: 'Enter total label',
      sort_order: 66,
    }),
    buildField({
      field_key: 'pricing_card_1_total_old_price',
      field_type: 'text',
      label: 'Pricing card 1 old total price',
      section: 'Pricing',
      helper_text: 'Example: $139',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 1 old total price' },
      default_value: '$139',
      placeholder: 'Enter old total price',
      sort_order: 67,
    }),
    buildField({
      field_key: 'pricing_card_1_total_new_price',
      field_type: 'text',
      label: 'Pricing card 1 new total price',
      section: 'Pricing',
      helper_text: 'Example: $69',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 1 new total price' },
      default_value: '$69',
      placeholder: 'Enter new total price',
      sort_order: 68,
    }),

    buildField({
      field_key: 'pricing_card_2_package_title',
      field_type: 'text',
      label: 'Pricing card 2 package title',
      section: 'Pricing',
      helper_text: 'Example: 6 X BOTTLE',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 2 package title' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter package title',
      sort_order: 69,
    }),
    buildField({
      field_key: 'pricing_card_2_supply_label',
      field_type: 'text',
      label: 'Pricing card 2 supply label',
      section: 'Pricing',
      helper_text: 'Example: 180 day Supply',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 2 supply label' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter supply label',
      sort_order: 70,
    }),
    buildField({
      field_key: 'pricing_card_2_image',
      field_type: 'image',
      label: 'Pricing card 2 image',
      section: 'Pricing',
      helper_text: 'Large pricing product image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 71,
    }),
    buildField({
      field_key: 'pricing_card_2_badge_text',
      field_type: 'text',
      label: 'Pricing card 2 badge text',
      section: 'Pricing',
      helper_text: 'Example: BEST VALUE',
      word_rule: { mode: 'range', min_words: 2, max_words: 4, label: 'Pricing card 2 badge text' },
      default_value: 'BEST VALUE',
      placeholder: 'Enter badge text',
      sort_order: 72,
    }),
    buildField({
      field_key: 'pricing_card_2_price_text',
      field_type: 'text',
      label: 'Pricing card 2 main price',
      section: 'Pricing',
      helper_text: 'Example: $49',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 2 main price' },
      default_value: '$49',
      placeholder: 'Enter main price',
      sort_order: 73,
    }),
    buildField({
      field_key: 'pricing_card_2_price_suffix',
      field_type: 'text',
      label: 'Pricing card 2 price suffix',
      section: 'Pricing',
      helper_text: 'Example: /Bottle',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 2 price suffix' },
      default_value: '/Bottle',
      placeholder: 'Enter price suffix',
      sort_order: 74,
    }),
    buildField({
      field_key: 'pricing_card_2_total_label',
      field_type: 'text',
      label: 'Pricing card 2 total label',
      section: 'Pricing',
      helper_text: 'Example: TOTAL:',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 2 total label' },
      default_value: 'TOTAL:',
      placeholder: 'Enter total label',
      sort_order: 75,
    }),
    buildField({
      field_key: 'pricing_card_2_total_old_price',
      field_type: 'text',
      label: 'Pricing card 2 old total price',
      section: 'Pricing',
      helper_text: 'Example: $1054',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 2 old total price' },
      default_value: '$1054',
      placeholder: 'Enter old total price',
      sort_order: 76,
    }),
    buildField({
      field_key: 'pricing_card_2_total_new_price',
      field_type: 'text',
      label: 'Pricing card 2 new total price',
      section: 'Pricing',
      helper_text: 'Example: $294',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 2 new total price' },
      default_value: '$294',
      placeholder: 'Enter new total price',
      sort_order: 77,
    }),

    buildField({
      field_key: 'pricing_card_3_package_title',
      field_type: 'text',
      label: 'Pricing card 3 package title',
      section: 'Pricing',
      helper_text: 'Example: 3 X BOTTLE',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 3 package title' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter package title',
      sort_order: 78,
    }),
    buildField({
      field_key: 'pricing_card_3_supply_label',
      field_type: 'text',
      label: 'Pricing card 3 supply label',
      section: 'Pricing',
      helper_text: 'Example: 90 day Supply',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Pricing card 3 supply label' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter supply label',
      sort_order: 79,
    }),
    buildField({
      field_key: 'pricing_card_3_image',
      field_type: 'image',
      label: 'Pricing card 3 image',
      section: 'Pricing',
      helper_text: 'Large pricing product image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 80,
    }),
    buildField({
      field_key: 'pricing_card_3_price_text',
      field_type: 'text',
      label: 'Pricing card 3 main price',
      section: 'Pricing',
      helper_text: 'Example: $59',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 3 main price' },
      default_value: '$59',
      placeholder: 'Enter main price',
      sort_order: 81,
    }),
    buildField({
      field_key: 'pricing_card_3_price_suffix',
      field_type: 'text',
      label: 'Pricing card 3 price suffix',
      section: 'Pricing',
      helper_text: 'Example: /Bottle',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 3 price suffix' },
      default_value: '/Bottle',
      placeholder: 'Enter price suffix',
      sort_order: 82,
    }),
    buildField({
      field_key: 'pricing_card_3_total_label',
      field_type: 'text',
      label: 'Pricing card 3 total label',
      section: 'Pricing',
      helper_text: 'Example: TOTAL:',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 3 total label' },
      default_value: 'TOTAL:',
      placeholder: 'Enter total label',
      sort_order: 83,
    }),
    buildField({
      field_key: 'pricing_card_3_total_old_price',
      field_type: 'text',
      label: 'Pricing card 3 old total price',
      section: 'Pricing',
      helper_text: 'Example: $139',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 3 old total price' },
      default_value: '$139',
      placeholder: 'Enter old total price',
      sort_order: 84,
    }),
    buildField({
      field_key: 'pricing_card_3_total_new_price',
      field_type: 'text',
      label: 'Pricing card 3 new total price',
      section: 'Pricing',
      helper_text: 'Example: $207',
      word_rule: { mode: 'range', min_words: 1, max_words: 2, label: 'Pricing card 3 new total price' },
      default_value: '$207',
      placeholder: 'Enter new total price',
      sort_order: 85,
    }),

    buildField({
      field_key: 'faq_section_title',
      field_type: 'text',
      label: 'FAQ section title',
      section: 'FAQ',
      helper_text: 'FAQ heading.',
      word_rule: { mode: 'range', min_words: 2, max_words: 6, label: 'FAQ section title' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 86,
    }),
    ...Array.from({ length: 10 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `faq_${i}_question`,
          field_type: 'text',
          label: `FAQ ${i} question`,
          section: 'FAQ',
          helper_text: 'FAQ question.',
          word_rule: { mode: 'range', min_words: 4, max_words: 10, label: `FAQ ${i} question` },
          default_value: makeLepresiumSentence(7, 7),
          placeholder: 'Enter at least 4 words',
          sort_order: 86 + i * 2 - 1,
        }),
        buildField({
          field_key: `faq_${i}_answer`,
          field_type: 'textarea',
          label: `FAQ ${i} answer`,
          section: 'FAQ',
          helper_text: 'FAQ answer.',
          word_rule: { mode: 'range', min_words: 12, max_words: 24, label: `FAQ ${i} answer` },
          default_value: makeLepresiumSentence(20, 20),
          placeholder: 'Enter at least 12 words',
          sort_order: 86 + i * 2,
        }),
      ];
    }).flat(),

    buildField({
      field_key: 'guarantee_title',
      field_type: 'text',
      label: 'Guarantee title',
      section: 'Guarantee',
      helper_text: 'Guarantee title.',
      word_rule: { mode: 'range', min_words: 2, max_words: 6, label: 'Guarantee title' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 107,
    }),
    buildField({
      field_key: 'guarantee_paragraph_1',
      field_type: 'textarea',
      label: 'Guarantee paragraph 1',
      section: 'Guarantee',
      helper_text: 'Guarantee paragraph.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'Guarantee paragraph 1' },
      default_value: makeLepresiumSentence(24, 24),
      placeholder: 'Enter at least 18 words',
      sort_order: 108,
    }),
    buildField({
      field_key: 'guarantee_paragraph_2',
      field_type: 'textarea',
      label: 'Guarantee paragraph 2',
      section: 'Guarantee',
      helper_text: 'Guarantee paragraph.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'Guarantee paragraph 2' },
      default_value: makeLepresiumSentence(24, 24),
      placeholder: 'Enter at least 18 words',
      sort_order: 109,
    }),
    buildField({
      field_key: 'guarantee_paragraph_3',
      field_type: 'text',
      label: 'Guarantee paragraph 3',
      section: 'Guarantee',
      helper_text: 'Guarantee closing line.',
      word_rule: { mode: 'range', min_words: 4, max_words: 10, label: 'Guarantee paragraph 3' },
      default_value: makeLepresiumSentence(6, 6),
      placeholder: 'Enter at least 4 words',
      sort_order: 110,
    }),
    buildField({
      field_key: 'special_offer_image',
      field_type: 'image',
      label: 'Special offer image',
      section: 'Special offer',
      helper_text: 'Special offer image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 111,
    }),
    buildField({
      field_key: 'special_offer_price_text',
      field_type: 'text',
      label: 'Special offer price text',
      section: 'Special offer',
      helper_text: 'Special offer price.',
      word_rule: { mode: 'range', min_words: 1, max_words: 4, label: 'Special offer price text' },
      default_value: makeLepresiumSentence(2, 2),
      placeholder: 'Enter at least 1 word',
      sort_order: 112,
    }),
    buildField({
      field_key: 'learn_more_title',
      field_type: 'text',
      label: 'Learn more title',
      section: 'Learn more',
      helper_text: 'Learn more title.',
      word_rule: { mode: 'range', min_words: 2, max_words: 6, label: 'Learn more title' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 113,
    }),
    ...Array.from({ length: 10 }, (_, index) =>
      buildField({
        field_key: `learn_more_paragraph_${index + 1}`,
        field_type: 'textarea',
        label: `Learn more paragraph ${index + 1}`,
        section: 'Learn more',
        helper_text: 'Long-form paragraph.',
        word_rule: { mode: 'range', min_words: 26, max_words: 60, label: `Learn more paragraph ${index + 1}` },
        default_value: makeLepresiumSentence(40, 40),
        placeholder: 'Enter at least 26 words',
        sort_order: 114 + index,
      })
    ),
  ];

  const ctaButtons = [
    buildButton({
      button_key: 'hero_primary_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Hero primary CTA',
      helper_text: 'Main hero CTA.',
      sort_order: 1,
    }),
    buildButton({
      button_key: 'hero_secondary_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Hero secondary CTA',
      helper_text: 'Second hero CTA.',
      sort_order: 2,
    }),
    buildButton({
      button_key: 'how_it_works_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'How this product works CTA',
      helper_text: 'CTA below how this product works section.',
      sort_order: 3,
    }),
    buildButton({
      button_key: 'ingredients_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Ingredients CTA',
      helper_text: 'CTA in ingredients section.',
      sort_order: 4,
    }),
    buildButton({
      button_key: 'pricing_card_1_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 1 CTA',
      helper_text: 'Pricing card 1 CTA.',
      sort_order: 5,
    }),
    buildButton({
      button_key: 'pricing_card_2_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 2 CTA',
      helper_text: 'Pricing card 2 CTA.',
      sort_order: 6,
    }),
    buildButton({
      button_key: 'pricing_card_3_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 3 CTA',
      helper_text: 'Pricing card 3 CTA.',
      sort_order: 7,
    }),
    buildButton({
      button_key: 'special_offer_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Special offer CTA',
      helper_text: 'Special offer CTA.',
      sort_order: 8,
    }),
  ];

  return {
    codeKeys: ['dxt_template_v1'],
    slugAliases: ['dxt'],
    nameAliases: ['dxt'],
    description: 'Locked Dxt long-form advertorial template with fixed sales sections and CTA slots.',
    fields,
    ctaButtons,
  };
}