function makeLepresiumWords(count) {
  return Array.from({ length: count }, () => 'Lepresium').join(' ');
}

function makeLepresiumSentence(minWords, maxWords) {
  const target = minWords === maxWords ? minWords : maxWords;
  return makeLepresiumWords(target);
}

function makeLepresiumUrl() {
  return 'https://supgad.com/lepresium';
}

function buildField({
  field_key,
  field_type = 'text',
  label,
  section,
  helper_text = '',
  required = true,
  word_rule = null,
  default_value = '',
  placeholder = '',
  sort_order,
}) {
  return {
    field_key,
    field_type,
    field_value: default_value,
    sort_order,
    meta: {
      label,
      section,
      helper_text,
      required,
      word_rule,
      placeholder,
      locked: true,
    },
  };
}

function buildButton({
  button_key,
  button_label,
  button_style = 'primary',
  label,
  helper_text = '',
  required = true,
  sort_order,
}) {
  return {
    button_key,
    button_label,
    button_url: makeLepresiumUrl(),
    button_style,
    open_in_new_tab: true,
    sort_order,
    meta: {
      label,
      helper_text,
      required,
      locked: true,
    },
  };
}

export default function createNeutralReviewTemplatePreset() {
  const fields = [
    buildField({
      field_key: 'top_bar_title',
      field_type: 'text',
      label: 'Top bar title',
      section: 'Top bar',
      helper_text: 'Full-width announcement text.',
      word_rule: { mode: 'exact', exact_words: 11, label: 'Top bar title' },
      default_value: makeLepresiumSentence(11, 11),
      placeholder: 'Enter exactly 11 words',
      sort_order: 1,
    }),
    buildField({
      field_key: 'hero_product_image',
      field_type: 'image',
      label: 'Hero product image',
      section: 'Hero left column',
      helper_text: 'Required main image. Keep same visual proportion.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 2,
    }),
    buildField({
      field_key: 'hero_review_text',
      field_type: 'text',
      label: 'Hero review text',
      section: 'Hero left column',
      helper_text: 'Review count text beside stars.',
      word_rule: { mode: 'range', min_words: 2, max_words: 4, label: 'Hero review text' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 3,
    }),
    buildField({
      field_key: 'hero_certification_image',
      field_type: 'image',
      label: 'Hero certification strip image',
      section: 'Hero left column',
      helper_text: 'Required certification/badge image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 4,
    }),
    buildField({
      field_key: 'hero_title',
      field_type: 'text',
      label: 'Hero title',
      section: 'Hero right column',
      helper_text: 'Main headline.',
      word_rule: { mode: 'range', min_words: 10, max_words: 12, label: 'Hero title' },
      default_value: makeLepresiumSentence(12, 12),
      placeholder: 'Enter at least 10 words',
      sort_order: 5,
    }),
    buildField({
      field_key: 'hero_intro_paragraph_1',
      field_type: 'textarea',
      label: 'Hero intro paragraph 1',
      section: 'Hero right column',
      helper_text: 'First intro paragraph.',
      word_rule: { mode: 'range', min_words: 30, max_words: 38, label: 'Hero intro paragraph 1' },
      default_value: makeLepresiumSentence(38, 38),
      placeholder: 'Enter at least 30 words',
      sort_order: 6,
    }),
    buildField({
      field_key: 'hero_intro_paragraph_2',
      field_type: 'textarea',
      label: 'Hero intro paragraph 2',
      section: 'Hero right column',
      helper_text: 'Second intro paragraph.',
      word_rule: { mode: 'range', min_words: 34, max_words: 42, label: 'Hero intro paragraph 2' },
      default_value: makeLepresiumSentence(42, 42),
      placeholder: 'Enter at least 34 words',
      sort_order: 7,
    }),
    buildField({
      field_key: 'hero_small_cta_line',
      field_type: 'text',
      label: 'Hero small CTA line',
      section: 'Hero right column',
      helper_text: 'Short underlined line above buttons.',
      word_rule: { mode: 'exact', exact_words: 7, label: 'Hero small CTA line' },
      default_value: makeLepresiumSentence(7, 7),
      placeholder: 'Enter exactly 7 words',
      sort_order: 8,
    }),
    buildField({
      field_key: 'hero_trust_item_1',
      field_type: 'text',
      label: 'Hero trust item 1',
      section: 'Hero right column',
      helper_text: 'First trust item under hero buttons.',
      word_rule: { mode: 'exact', exact_words: 2, label: 'Hero trust item 1' },
      default_value: makeLepresiumSentence(2, 2),
      placeholder: 'Enter exactly 2 words',
      sort_order: 9,
    }),
    buildField({
      field_key: 'hero_trust_item_2',
      field_type: 'text',
      label: 'Hero trust item 2',
      section: 'Hero right column',
      helper_text: 'Second trust item under hero buttons.',
      word_rule: { mode: 'exact', exact_words: 2, label: 'Hero trust item 2' },
      default_value: makeLepresiumSentence(2, 2),
      placeholder: 'Enter exactly 2 words',
      sort_order: 10,
    }),
    buildField({
      field_key: 'hero_trust_item_3',
      field_type: 'text',
      label: 'Hero trust item 3',
      section: 'Hero right column',
      helper_text: 'Third trust item under hero buttons.',
      word_rule: { mode: 'exact', exact_words: 2, label: 'Hero trust item 3' },
      default_value: makeLepresiumSentence(2, 2),
      placeholder: 'Enter exactly 2 words',
      sort_order: 11,
    }),
    buildField({
      field_key: 'how_this_product_works_title',
      field_type: 'text',
      label: 'How This Product Works title',
      section: 'How this product works',
      helper_text: 'Neutral section title.',
      word_rule: { mode: 'exact', exact_words: 4, label: 'How This Product Works title' },
      default_value: 'How This Product Works',
      placeholder: 'Enter exactly 4 words',
      sort_order: 12,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_1',
      field_type: 'textarea',
      label: 'How this product works paragraph 1',
      section: 'How this product works',
      helper_text: 'Required paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 18,
        max_words: 24,
        label: 'How this product works paragraph 1',
      },
      default_value: makeLepresiumSentence(24, 24),
      placeholder: 'Enter at least 18 words',
      sort_order: 13,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_2',
      field_type: 'textarea',
      label: 'How this product works paragraph 2',
      section: 'How this product works',
      helper_text: 'Required paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 22,
        max_words: 30,
        label: 'How this product works paragraph 2',
      },
      default_value: makeLepresiumSentence(30, 30),
      placeholder: 'Enter at least 22 words',
      sort_order: 14,
    }),
    buildField({
      field_key: 'how_this_product_works_paragraph_3',
      field_type: 'textarea',
      label: 'How this product works paragraph 3',
      section: 'How this product works',
      helper_text: 'Required paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 24,
        max_words: 34,
        label: 'How this product works paragraph 3',
      },
      default_value: makeLepresiumSentence(34, 34),
      placeholder: 'Enter at least 24 words',
      sort_order: 15,
    }),
    buildField({
      field_key: 'how_this_product_works_image',
      field_type: 'image',
      label: 'How this product works image',
      section: 'How this product works',
      helper_text: 'Required right-side image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 16,
    }),
    buildField({
      field_key: 'ingredients_section_title',
      field_type: 'text',
      label: 'Ingredients section title',
      section: 'Ingredients / blend',
      helper_text: 'Neutral section heading.',
      word_rule: { mode: 'range', min_words: 6, max_words: 10, label: 'Ingredients section title' },
      default_value: makeLepresiumSentence(8, 8),
      placeholder: 'Enter at least 6 words',
      sort_order: 17,
    }),
    buildField({
      field_key: 'ingredients_intro',
      field_type: 'textarea',
      label: 'Ingredients intro',
      section: 'Ingredients / blend',
      helper_text: 'Short intro paragraph.',
      word_rule: { mode: 'range', min_words: 14, max_words: 18, label: 'Ingredients intro' },
      default_value: makeLepresiumSentence(18, 18),
      placeholder: 'Enter at least 14 words',
      sort_order: 18,
    }),
    ...Array.from({ length: 5 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `ingredient_${i}_title`,
          field_type: 'text',
          label: `Ingredient ${i} title`,
          section: 'Ingredients / blend',
          helper_text: 'Ingredient item title.',
          word_rule: { mode: 'range', min_words: 1, max_words: 4, label: `Ingredient ${i} title` },
          default_value: makeLepresiumSentence(3, 3),
          placeholder: 'Enter at least 1 word',
          sort_order: 18 + i * 2 - 1,
        }),
        buildField({
          field_key: `ingredient_${i}_text`,
          field_type: 'text',
          label: `Ingredient ${i} text`,
          section: 'Ingredients / blend',
          helper_text: 'Ingredient support text.',
          word_rule: { mode: 'range', min_words: 5, max_words: 9, label: `Ingredient ${i} text` },
          default_value: makeLepresiumSentence(9, 9),
          placeholder: 'Enter at least 5 words',
          sort_order: 18 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'ingredients_closing_line',
      field_type: 'textarea',
      label: 'Ingredients closing line',
      section: 'Ingredients / blend',
      helper_text: 'Closing support line.',
      word_rule: { mode: 'range', min_words: 14, max_words: 18, label: 'Ingredients closing line' },
      default_value: makeLepresiumSentence(18, 18),
      placeholder: 'Enter at least 14 words',
      sort_order: 29,
    }),
    buildField({
      field_key: 'ingredients_image',
      field_type: 'image',
      label: 'Ingredients image',
      section: 'Ingredients / blend',
      helper_text: 'Required image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 30,
    }),
    buildField({
      field_key: 'what_makes_this_product_different_title',
      field_type: 'text',
      label: 'What makes this product different title',
      section: 'What makes this product different',
      helper_text: 'Neutral section title.',
      word_rule: {
        mode: 'range',
        min_words: 5,
        max_words: 7,
        label: 'What makes this product different title',
      },
      default_value: 'What Makes This Product Different',
      placeholder: 'Enter at least 5 words',
      sort_order: 31,
    }),
    buildField({
      field_key: 'difference_intro',
      field_type: 'textarea',
      label: 'Difference intro',
      section: 'What makes this product different',
      helper_text: 'Intro paragraph.',
      word_rule: { mode: 'range', min_words: 26, max_words: 34, label: 'Difference intro' },
      default_value: makeLepresiumSentence(34, 34),
      placeholder: 'Enter at least 26 words',
      sort_order: 32,
    }),
    ...Array.from({ length: 4 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `difference_item_${i}_title`,
          field_type: 'text',
          label: `Difference item ${i} title`,
          section: 'What makes this product different',
          helper_text: 'Feature mini heading.',
          word_rule: {
            mode: 'range',
            min_words: 4,
            max_words: 6,
            label: `Difference item ${i} title`,
          },
          default_value: makeLepresiumSentence(6, 6),
          placeholder: 'Enter at least 4 words',
          sort_order: 32 + i * 2 - 1,
        }),
        buildField({
          field_key: `difference_item_${i}_text`,
          field_type: 'textarea',
          label: `Difference item ${i} text`,
          section: 'What makes this product different',
          helper_text: 'Feature paragraph.',
          word_rule: {
            mode: 'range',
            min_words: 20,
            max_words: 36,
            label: `Difference item ${i} text`,
          },
          default_value: makeLepresiumSentence(36, 36),
          placeholder: 'Enter at least 20 words',
          sort_order: 32 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'benefits_title',
      field_type: 'text',
      label: 'Benefits title',
      section: 'Benefits',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 3, max_words: 5, label: 'Benefits title' },
      default_value: 'Benefits Of This Product',
      placeholder: 'Enter at least 3 words',
      sort_order: 41,
    }),
    buildField({
      field_key: 'benefits_intro',
      field_type: 'textarea',
      label: 'Benefits intro',
      section: 'Benefits',
      helper_text: 'Intro paragraph.',
      word_rule: { mode: 'range', min_words: 24, max_words: 30, label: 'Benefits intro' },
      default_value: makeLepresiumSentence(30, 30),
      placeholder: 'Enter at least 24 words',
      sort_order: 42,
    }),
    ...Array.from({ length: 7 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `benefit_${i}_title`,
          field_type: 'text',
          label: `Benefit ${i} title`,
          section: 'Benefits',
          helper_text: 'Benefit title.',
          word_rule: { mode: 'range', min_words: 3, max_words: 5, label: `Benefit ${i} title` },
          default_value: makeLepresiumSentence(4, 4),
          placeholder: 'Enter at least 3 words',
          sort_order: 42 + i * 2 - 1,
        }),
        buildField({
          field_key: `benefit_${i}_text`,
          field_type: 'text',
          label: `Benefit ${i} text`,
          section: 'Benefits',
          helper_text: 'Benefit short support line.',
          word_rule: { mode: 'range', min_words: 10, max_words: 16, label: `Benefit ${i} text` },
          default_value: makeLepresiumSentence(16, 16),
          placeholder: 'Enter at least 10 words',
          sort_order: 42 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'benefits_closing_line',
      field_type: 'textarea',
      label: 'Benefits closing line',
      section: 'Benefits',
      helper_text: 'Closing line under benefits.',
      word_rule: { mode: 'range', min_words: 18, max_words: 22, label: 'Benefits closing line' },
      default_value: makeLepresiumSentence(22, 22),
      placeholder: 'Enter at least 18 words',
      sort_order: 57,
    }),
    buildField({
      field_key: 'testimonials_title',
      field_type: 'text',
      label: 'Testimonials title',
      section: 'Testimonials',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 4, max_words: 6, label: 'Testimonials title' },
      default_value: makeLepresiumSentence(5, 5),
      placeholder: 'Enter at least 4 words',
      sort_order: 58,
    }),
    ...Array.from({ length: 3 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `testimonial_${i}_image`,
          field_type: 'image',
          label: `Testimonial ${i} image`,
          section: 'Testimonials',
          helper_text: 'Required reviewer image.',
          default_value: '',
          placeholder: 'Upload image or paste image URL',
          sort_order: 58 + i * 3 - 2,
        }),
        buildField({
          field_key: `testimonial_${i}_name_line`,
          field_type: 'text',
          label: `Testimonial ${i} name line`,
          section: 'Testimonials',
          helper_text: 'Name/location line.',
          word_rule: {
            mode: 'range',
            min_words: 3,
            max_words: 5,
            label: `Testimonial ${i} name line`,
          },
          default_value: makeLepresiumSentence(5, 5),
          placeholder: 'Enter at least 3 words',
          sort_order: 58 + i * 3 - 1,
        }),
        buildField({
          field_key: `testimonial_${i}_text`,
          field_type: 'textarea',
          label: `Testimonial ${i} text`,
          section: 'Testimonials',
          helper_text: 'Required testimonial content.',
          word_rule: {
            mode: 'range',
            min_words: 24,
            max_words: 40,
            label: `Testimonial ${i} text`,
          },
          default_value: makeLepresiumSentence(40, 40),
          placeholder: 'Enter at least 24 words',
          sort_order: 58 + i * 3,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'pricing_title',
      field_type: 'text',
      label: 'Pricing section title',
      section: 'Pricing',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 6, max_words: 10, label: 'Pricing section title' },
      default_value: makeLepresiumSentence(8, 8),
      placeholder: 'Enter at least 6 words',
      sort_order: 68,
    }),
    ...Array.from({ length: 3 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `pricing_card_${i}_package_title`,
          field_type: 'text',
          label: `Pricing card ${i} package title`,
          section: 'Pricing',
          helper_text: 'Package title.',
          word_rule: {
            mode: 'exact',
            exact_words: 3,
            label: `Pricing card ${i} package title`,
          },
          default_value: makeLepresiumSentence(3, 3),
          placeholder: 'Enter exactly 3 words',
          sort_order: 68 + i * 6 - 5,
        }),
        buildField({
          field_key: `pricing_card_${i}_supply_label`,
          field_type: 'text',
          label: `Pricing card ${i} supply label`,
          section: 'Pricing',
          helper_text: 'Supply label.',
          word_rule: {
            mode: 'exact',
            exact_words: 3,
            label: `Pricing card ${i} supply label`,
          },
          default_value: makeLepresiumSentence(3, 3),
          placeholder: 'Enter exactly 3 words',
          sort_order: 68 + i * 6 - 4,
        }),
        buildField({
          field_key: `pricing_card_${i}_image`,
          field_type: 'image',
          label: `Pricing card ${i} image`,
          section: 'Pricing',
          helper_text: 'Required pack image.',
          default_value: '',
          placeholder: 'Upload image or paste image URL',
          sort_order: 68 + i * 6 - 3,
        }),
        buildField({
          field_key: `pricing_card_${i}_price_text`,
          field_type: 'text',
          label: `Pricing card ${i} price text`,
          section: 'Pricing',
          helper_text: 'Price display text.',
          word_rule: {
            mode: 'range',
            min_words: 1,
            max_words: 3,
            label: `Pricing card ${i} price text`,
          },
          default_value: makeLepresiumSentence(2, 2),
          placeholder: 'Enter at least 1 word',
          sort_order: 68 + i * 6 - 2,
        }),
        buildField({
          field_key: `pricing_card_${i}_total_text`,
          field_type: 'text',
          label: `Pricing card ${i} total text`,
          section: 'Pricing',
          helper_text: 'Total line text.',
          word_rule: {
            mode: 'range',
            min_words: 2,
            max_words: 5,
            label: `Pricing card ${i} total text`,
          },
          default_value: makeLepresiumSentence(4, 4),
          placeholder: 'Enter at least 2 words',
          sort_order: 68 + i * 6 - 1,
        }),
        buildField({
          field_key: `pricing_card_${i}_payments_image`,
          field_type: 'image',
          label: `Pricing card ${i} payments image`,
          section: 'Pricing',
          helper_text: 'Required payment methods strip.',
          default_value: '',
          placeholder: 'Upload image or paste image URL',
          sort_order: 68 + i * 6,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'bonus_section_title',
      field_type: 'text',
      label: 'Bonus section title',
      section: 'Bonuses',
      helper_text: 'Bonus section heading.',
      word_rule: { mode: 'range', min_words: 6, max_words: 10, label: 'Bonus section title' },
      default_value: makeLepresiumSentence(8, 8),
      placeholder: 'Enter at least 6 words',
      sort_order: 87,
    }),
    ...Array.from({ length: 3 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `bonus_${i}_image`,
          field_type: 'image',
          label: `Bonus ${i} image`,
          section: 'Bonuses',
          helper_text: 'Required bonus image.',
          default_value: '',
          placeholder: 'Upload image or paste image URL',
          sort_order: 87 + i * 4 - 3,
        }),
        buildField({
          field_key: `bonus_${i}_title`,
          field_type: 'text',
          label: `Bonus ${i} title`,
          section: 'Bonuses',
          helper_text: 'Bonus title.',
          word_rule: { mode: 'range', min_words: 4, max_words: 8, label: `Bonus ${i} title` },
          default_value: makeLepresiumSentence(8, 8),
          placeholder: 'Enter at least 4 words',
          sort_order: 87 + i * 4 - 2,
        }),
        buildField({
          field_key: `bonus_${i}_price_line`,
          field_type: 'text',
          label: `Bonus ${i} price line`,
          section: 'Bonuses',
          helper_text: 'Price/free line.',
          word_rule: { mode: 'range', min_words: 2, max_words: 6, label: `Bonus ${i} price line` },
          default_value: makeLepresiumSentence(4, 4),
          placeholder: 'Enter at least 2 words',
          sort_order: 87 + i * 4 - 1,
        }),
        buildField({
          field_key: `bonus_${i}_text`,
          field_type: 'textarea',
          label: `Bonus ${i} text`,
          section: 'Bonuses',
          helper_text: 'Bonus description.',
          word_rule: { mode: 'range', min_words: 18, max_words: 28, label: `Bonus ${i} text` },
          default_value: makeLepresiumSentence(28, 28),
          placeholder: 'Enter at least 18 words',
          sort_order: 87 + i * 4,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'faq_section_title',
      field_type: 'text',
      label: 'FAQ section title',
      section: 'FAQ',
      helper_text: 'FAQ section heading.',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'FAQ section title' },
      default_value: 'This Product FAQ',
      placeholder: 'Enter at least 2 words',
      sort_order: 100,
    }),
    ...Array.from({ length: 10 }, (_, index) => {
      const i = index + 1;
      return [
        buildField({
          field_key: `faq_${i}_question`,
          field_type: 'text',
          label: `FAQ ${i} question`,
          section: 'FAQ',
          helper_text: 'Required question.',
          word_rule: { mode: 'range', min_words: 4, max_words: 9, label: `FAQ ${i} question` },
          default_value: makeLepresiumSentence(7, 7),
          placeholder: 'Enter at least 4 words',
          sort_order: 100 + i * 2 - 1,
        }),
        buildField({
          field_key: `faq_${i}_answer`,
          field_type: 'textarea',
          label: `FAQ ${i} answer`,
          section: 'FAQ',
          helper_text: 'Required answer.',
          word_rule: { mode: 'range', min_words: 12, max_words: 24, label: `FAQ ${i} answer` },
          default_value: makeLepresiumSentence(24, 24),
          placeholder: 'Enter at least 12 words',
          sort_order: 100 + i * 2,
        }),
      ];
    }).flat(),
    buildField({
      field_key: 'guarantee_badge_image',
      field_type: 'image',
      label: 'Guarantee badge image',
      section: 'Guarantee',
      helper_text: 'Required guarantee badge.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 121,
    }),
    buildField({
      field_key: 'guarantee_title',
      field_type: 'text',
      label: 'Guarantee title',
      section: 'Guarantee',
      helper_text: 'Guarantee heading.',
      word_rule: { mode: 'range', min_words: 6, max_words: 8, label: 'Guarantee title' },
      default_value: makeLepresiumSentence(8, 8),
      placeholder: 'Enter at least 6 words',
      sort_order: 122,
    }),
    buildField({
      field_key: 'guarantee_paragraph_1',
      field_type: 'textarea',
      label: 'Guarantee paragraph 1',
      section: 'Guarantee',
      helper_text: 'Required paragraph.',
      word_rule: { mode: 'range', min_words: 28, max_words: 38, label: 'Guarantee paragraph 1' },
      default_value: makeLepresiumSentence(38, 38),
      placeholder: 'Enter at least 28 words',
      sort_order: 123,
    }),
    buildField({
      field_key: 'guarantee_paragraph_2',
      field_type: 'textarea',
      label: 'Guarantee paragraph 2',
      section: 'Guarantee',
      helper_text: 'Required paragraph.',
      word_rule: { mode: 'range', min_words: 22, max_words: 30, label: 'Guarantee paragraph 2' },
      default_value: makeLepresiumSentence(30, 30),
      placeholder: 'Enter at least 22 words',
      sort_order: 124,
    }),
    buildField({
      field_key: 'guarantee_paragraph_3',
      field_type: 'text',
      label: 'Guarantee paragraph 3',
      section: 'Guarantee',
      helper_text: 'Short closing line.',
      word_rule: { mode: 'range', min_words: 4, max_words: 8, label: 'Guarantee paragraph 3' },
      default_value: makeLepresiumSentence(6, 6),
      placeholder: 'Enter at least 4 words',
      sort_order: 125,
    }),
    buildField({
      field_key: 'special_offer_title',
      field_type: 'text',
      label: 'Special offer title',
      section: 'Special offer',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 8, max_words: 14, label: 'Special offer title' },
      default_value: makeLepresiumSentence(12, 12),
      placeholder: 'Enter at least 8 words',
      sort_order: 126,
    }),
    buildField({
      field_key: 'special_offer_image',
      field_type: 'image',
      label: 'Special offer image',
      section: 'Special offer',
      helper_text: 'Required offer image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 127,
    }),
    buildField({
      field_key: 'special_offer_price_text',
      field_type: 'text',
      label: 'Special offer price text',
      section: 'Special offer',
      helper_text: 'Price text.',
      word_rule: { mode: 'range', min_words: 2, max_words: 6, label: 'Special offer price text' },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 2 words',
      sort_order: 128,
    }),
    buildField({
      field_key: 'learn_more_title',
      field_type: 'text',
      label: 'Learn more title',
      section: 'Learn more',
      helper_text: 'Section title.',
      word_rule: { mode: 'exact', exact_words: 5, label: 'Learn more title' },
      default_value: 'Learn More About This Product',
      placeholder: 'Enter exactly 5 words',
      sort_order: 129,
    }),
    ...Array.from({ length: 8 }, (_, index) =>
      buildField({
        field_key: `learn_more_paragraph_${index + 1}`,
        field_type: 'textarea',
        label: `Learn more paragraph ${index + 1}`,
        section: 'Learn more',
        helper_text: 'Long-form paragraph.',
        word_rule: {
          mode: 'range',
          min_words: 45,
          max_words: 75,
          label: `Learn more paragraph ${index + 1}`,
        },
        default_value: makeLepresiumSentence(75, 75),
        placeholder: 'Enter at least 45 words',
        sort_order: 130 + index,
      })
    ),
    buildField({
      field_key: 'scientific_references_title',
      field_type: 'text',
      label: 'Scientific references title',
      section: 'Scientific references',
      helper_text: 'Section title.',
      word_rule: { mode: 'range', min_words: 2, max_words: 5, label: 'Scientific references title' },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter at least 2 words',
      sort_order: 138,
    }),
    buildField({
      field_key: 'scientific_references_logo_strip',
      field_type: 'image',
      label: 'Scientific references logo strip',
      section: 'Scientific references',
      helper_text: 'Required image.',
      default_value: '',
      placeholder: 'Upload image or paste image URL',
      sort_order: 139,
    }),
    buildField({
      field_key: 'advertorial_notice',
      field_type: 'textarea',
      label: 'Advertorial notice',
      section: 'Legal',
      helper_text: 'Required legal notice.',
      word_rule: { mode: 'range', min_words: 18, max_words: 30, label: 'Advertorial notice' },
      default_value: makeLepresiumSentence(28, 28),
      placeholder: 'Enter at least 18 words',
      sort_order: 140,
    }),
    buildField({
      field_key: 'platform_notice',
      field_type: 'textarea',
      label: 'Platform notice',
      section: 'Legal',
      helper_text: 'Required platform notice.',
      word_rule: { mode: 'range', min_words: 14, max_words: 24, label: 'Platform notice' },
      default_value: makeLepresiumSentence(22, 22),
      placeholder: 'Enter at least 14 words',
      sort_order: 141,
    }),
    buildField({
      field_key: 'legal_disclaimer_title',
      field_type: 'text',
      label: 'Disclaimer title',
      section: 'Legal',
      helper_text: 'Legal section title.',
      word_rule: { mode: 'exact', exact_words: 1, label: 'Disclaimer title' },
      default_value: 'Disclaimer',
      placeholder: 'Enter exactly 1 word',
      sort_order: 142,
    }),
    buildField({
      field_key: 'legal_disclaimer_paragraph_1',
      field_type: 'textarea',
      label: 'Disclaimer paragraph 1',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: { mode: 'range', min_words: 28, max_words: 42, label: 'Disclaimer paragraph 1' },
      default_value: makeLepresiumSentence(42, 42),
      placeholder: 'Enter at least 28 words',
      sort_order: 143,
    }),
    buildField({
      field_key: 'legal_disclaimer_paragraph_2',
      field_type: 'textarea',
      label: 'Disclaimer paragraph 2',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: { mode: 'range', min_words: 20, max_words: 32, label: 'Disclaimer paragraph 2' },
      default_value: makeLepresiumSentence(32, 32),
      placeholder: 'Enter at least 20 words',
      sort_order: 144,
    }),
    buildField({
      field_key: 'affiliate_editorial_disclosure_title',
      field_type: 'text',
      label: 'Affiliate & editorial disclosure title',
      section: 'Legal',
      helper_text: 'Required legal title.',
      word_rule: {
        mode: 'range',
        min_words: 3,
        max_words: 5,
        label: 'Affiliate & editorial disclosure title',
      },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 3 words',
      sort_order: 145,
    }),
    buildField({
      field_key: 'affiliate_editorial_disclosure_paragraph_1',
      field_type: 'textarea',
      label: 'Affiliate & editorial disclosure paragraph 1',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 26,
        max_words: 40,
        label: 'Affiliate & editorial disclosure paragraph 1',
      },
      default_value: makeLepresiumSentence(40, 40),
      placeholder: 'Enter at least 26 words',
      sort_order: 146,
    }),
    buildField({
      field_key: 'affiliate_editorial_disclosure_paragraph_2',
      field_type: 'textarea',
      label: 'Affiliate & editorial disclosure paragraph 2',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 18,
        max_words: 30,
        label: 'Affiliate & editorial disclosure paragraph 2',
      },
      default_value: makeLepresiumSentence(30, 30),
      placeholder: 'Enter at least 18 words',
      sort_order: 147,
    }),
    buildField({
      field_key: 'trademark_disclaimer_title',
      field_type: 'text',
      label: 'Trademark disclaimer title',
      section: 'Legal',
      helper_text: 'Required legal title.',
      word_rule: {
        mode: 'range',
        min_words: 2,
        max_words: 4,
        label: 'Trademark disclaimer title',
      },
      default_value: makeLepresiumSentence(3, 3),
      placeholder: 'Enter at least 2 words',
      sort_order: 148,
    }),
    buildField({
      field_key: 'trademark_disclaimer_paragraph',
      field_type: 'textarea',
      label: 'Trademark disclaimer paragraph',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 20,
        max_words: 30,
        label: 'Trademark disclaimer paragraph',
      },
      default_value: makeLepresiumSentence(30, 30),
      placeholder: 'Enter at least 20 words',
      sort_order: 149,
    }),
    buildField({
      field_key: 'fda_compliance_statement_title',
      field_type: 'text',
      label: 'FDA compliance statement title',
      section: 'Legal',
      helper_text: 'Required legal title.',
      word_rule: {
        mode: 'range',
        min_words: 3,
        max_words: 5,
        label: 'FDA compliance statement title',
      },
      default_value: makeLepresiumSentence(4, 4),
      placeholder: 'Enter at least 3 words',
      sort_order: 150,
    }),
    buildField({
      field_key: 'fda_compliance_statement_paragraph_1',
      field_type: 'textarea',
      label: 'FDA compliance statement paragraph 1',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 24,
        max_words: 36,
        label: 'FDA compliance statement paragraph 1',
      },
      default_value: makeLepresiumSentence(36, 36),
      placeholder: 'Enter at least 24 words',
      sort_order: 151,
    }),
    buildField({
      field_key: 'fda_compliance_statement_paragraph_2',
      field_type: 'textarea',
      label: 'FDA compliance statement paragraph 2',
      section: 'Legal',
      helper_text: 'Required legal paragraph.',
      word_rule: {
        mode: 'range',
        min_words: 14,
        max_words: 24,
        label: 'FDA compliance statement paragraph 2',
      },
      default_value: makeLepresiumSentence(24, 24),
      placeholder: 'Enter at least 14 words',
      sort_order: 152,
    }),
  ];

  const ctaButtons = [
    buildButton({
      button_key: 'hero_primary_cta',
      button_label: makeLepresiumSentence(4, 4),
      button_style: 'primary',
      label: 'Hero primary CTA',
      helper_text: 'Main hero CTA. Exactly 4 words.',
      sort_order: 1,
    }),
    buildButton({
      button_key: 'hero_secondary_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'secondary',
      label: 'Hero secondary CTA',
      helper_text: 'Secondary hero CTA. Exactly 2 words.',
      sort_order: 2,
    }),
    buildButton({
      button_key: 'how_it_works_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'secondary',
      label: 'How this product works CTA',
      helper_text: 'CTA under how this product works. Exactly 2 words.',
      sort_order: 3,
    }),
    buildButton({
      button_key: 'ingredients_cta',
      button_label: makeLepresiumSentence(3, 3),
      button_style: 'primary',
      label: 'Ingredients CTA',
      helper_text: 'CTA in ingredients section. Exactly 3 words.',
      sort_order: 4,
    }),
    buildButton({
      button_key: 'pricing_card_1_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 1 CTA',
      helper_text: 'Pricing card 1 CTA. Exactly 2 words.',
      sort_order: 5,
    }),
    buildButton({
      button_key: 'pricing_card_2_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 2 CTA',
      helper_text: 'Pricing card 2 CTA. Exactly 2 words.',
      sort_order: 6,
    }),
    buildButton({
      button_key: 'pricing_card_3_cta',
      button_label: makeLepresiumSentence(2, 2),
      button_style: 'primary',
      label: 'Pricing card 3 CTA',
      helper_text: 'Pricing card 3 CTA. Exactly 2 words.',
      sort_order: 7,
    }),
    buildButton({
      button_key: 'special_offer_cta',
      button_label: makeLepresiumSentence(5, 5),
      button_style: 'primary',
      label: 'Special offer CTA',
      helper_text: 'Special offer CTA. Exactly 5 words.',
      sort_order: 8,
    }),
  ];

  return {
    codeKeys: ['neutral_review_template_v1', 'blog_review_locked_v1', 'dummy_review_template_v1'],
    slugAliases: ['neutral-review-template-v1', 'dummy-review-template-v1'],
    nameAliases: ['neutral review template', 'dummy review template', 'blog review template'],
    description:
      'Locked review-style blog template with compulsory Lepresium dummy content and strict field validation.',
    fields,
    ctaButtons,
  };
}