function createField({
  field_key,
  field_type = 'text',
  field_value = '',
  sort_order,
  label,
  section,
  helper_text = '',
  required = false,
  placeholder = '',
  locked = false,
  word_rule = null,
}) {
  return {
    field_key,
    field_type,
    field_value,
    sort_order,
    meta: {
      label,
      section,
      helper_text,
      required,
      word_rule,
      placeholder,
      locked,
    },
  };
}

function createButton({
  button_key,
  button_label,
  button_url = '',
  button_style = 'primary',
  open_in_new_tab = true,
  sort_order,
  label,
  helper_text = '',
  required = true,
  locked = false,
}) {
  return {
    button_key,
    button_label,
    button_url,
    button_style,
    open_in_new_tab,
    sort_order,
    meta: {
      label,
      helper_text,
      required,
      locked,
    },
  };
}

const SimplePostsTemplatePreset = {
  name: 'Simple Posts',
  code: 'simple-posts',
  slug: 'simple-posts',
  type: 'post',
  category: 'Product Review',
  description:
    'Clean long-form product blog post template with optional hidden ad placements, sidebar blocks, quick summary, features, pros and cons, FAQ, final verdict, email capture, and related posts.',

  codeKeys: ['simple_posts_template_v1', 'simple-posts'],
  slugAliases: ['simple-posts'],
  nameAliases: ['simple posts', 'simple post', 'simple product blog post template'],

  fields: [
    createField({
      field_key: 'top_notice_text',
      field_type: 'text',
      sort_order: 1,
      label: 'Notice Text',
      section: 'Top Notice Bar',
      helper_text: 'Shown in the slim announcement bar above the header.',
      placeholder: 'Limited time: Get 20% off all tools this week!',
    }),
    createField({
      field_key: 'top_notice_link_label',
      field_type: 'text',
      sort_order: 2,
      label: 'Notice Link Label',
      section: 'Top Notice Bar',
      helper_text: 'Optional link label beside the notice text.',
      placeholder: 'Learn more',
    }),
    createField({
      field_key: 'top_notice_link_url',
      field_type: 'url',
      sort_order: 3,
      label: 'Notice Link URL',
      section: 'Top Notice Bar',
      helper_text: 'Optional notice link URL.',
      placeholder: 'https://supgad.com/your-link',
    }),

    createField({
      field_key: 'hero_category_label',
      field_type: 'text',
      sort_order: 4,
      label: 'Category Label',
      section: 'Hero Section',
      helper_text: 'Small blue category tag above the post title.',
      placeholder: 'Productivity',
    }),
    createField({
      field_key: 'hero_title',
      field_type: 'text',
      sort_order: 5,
      label: 'Hero Title',
      section: 'Hero Section',
      helper_text: 'Main post headline shown at the top of the article.',
      required: false,
      placeholder: 'ProductX Review: The All-in-One Tool for Modern Teams',
    }),
    createField({
      field_key: 'hero_subtitle',
      field_type: 'textarea',
      sort_order: 6,
      label: 'Hero Subtitle',
      section: 'Hero Section',
      helper_text: 'Short description below the main title.',
      placeholder: 'Deep dive into features, pricing, pros and cons, and who it’s best for.',
    }),
    createField({
      field_key: 'hero_author_name',
      field_type: 'text',
      sort_order: 7,
      label: 'Author Name',
      section: 'Hero Section',
      helper_text: 'Author name shown in the post meta row.',
      placeholder: 'Jane Doe',
    }),
    createField({
      field_key: 'hero_author_image',
      field_type: 'image',
      sort_order: 8,
      label: 'Author Image',
      section: 'Hero Section',
      helper_text: 'Optional author avatar image.',
      placeholder: 'Upload image or paste image URL',
    }),
    createField({
      field_key: 'hero_date_text',
      field_type: 'text',
      sort_order: 9,
      label: 'Date Text',
      section: 'Hero Section',
      helper_text: 'Date shown in the post meta row.',
      placeholder: 'May 15, 2024',
    }),
    createField({
      field_key: 'hero_read_time',
      field_type: 'text',
      sort_order: 10,
      label: 'Read Time',
      section: 'Hero Section',
      helper_text: 'Estimated reading time shown in the post meta row.',
      placeholder: '8 min read',
    }),
    createField({
      field_key: 'hero_image',
      field_type: 'image',
      sort_order: 11,
      label: 'Hero Image',
      section: 'Hero Section',
      helper_text: 'Main wide image below the title and meta row.',
      placeholder: 'Upload image or paste image URL',
    }),

    createField({
      field_key: 'summary_label',
      field_type: 'text',
      sort_order: 12,
      label: 'Summary Label',
      section: 'Quick Summary',
      helper_text: 'Left label inside the quick summary card.',
      placeholder: 'Quick Summary',
    }),
    createField({
      field_key: 'summary_verdict_label',
      field_type: 'text',
      sort_order: 13,
      label: 'Verdict Label',
      section: 'Quick Summary',
      helper_text: 'Bold verdict label before the summary text.',
      placeholder: 'Short Verdict:',
    }),
    createField({
      field_key: 'summary_verdict_text',
      field_type: 'textarea',
      sort_order: 14,
      label: 'Verdict Text',
      section: 'Quick Summary',
      helper_text: 'Short verdict shown inside the quick summary card.',
      placeholder: 'ProductX is a powerful all-in-one platform that simplifies workflows and boosts team productivity.',
    }),
    createField({
      field_key: 'summary_point_1',
      field_type: 'text',
      sort_order: 15,
      label: 'Summary Point 1',
      section: 'Quick Summary',
      helper_text: 'First checked point in the quick summary card.',
      placeholder: 'Easy to use with a clean, modern interface',
    }),
    createField({
      field_key: 'summary_point_2',
      field_type: 'text',
      sort_order: 16,
      label: 'Summary Point 2',
      section: 'Quick Summary',
      helper_text: 'Second checked point in the quick summary card.',
      placeholder: 'Packed with features that cover every workflow',
    }),
    createField({
      field_key: 'summary_point_3',
      field_type: 'text',
      sort_order: 17,
      label: 'Summary Point 3',
      section: 'Quick Summary',
      helper_text: 'Third checked point in the quick summary card.',
      placeholder: 'Great value for teams of all sizes',
    }),

    createField({
      field_key: 'intro_title',
      field_type: 'text',
      sort_order: 18,
      label: 'Introduction Title',
      section: 'Introduction',
      helper_text: 'Heading for the opening section.',
      placeholder: 'Introduction',
    }),
    createField({
      field_key: 'intro_paragraph_1',
      field_type: 'textarea',
      sort_order: 19,
      label: 'Introduction Paragraph 1',
      section: 'Introduction',
      helper_text: 'Opening paragraph for the article.',
      placeholder: 'Write the first introduction paragraph.',
    }),
    createField({
      field_key: 'intro_paragraph_2',
      field_type: 'textarea',
      sort_order: 20,
      label: 'Introduction Paragraph 2',
      section: 'Introduction',
      helper_text: 'Second introduction paragraph.',
      placeholder: 'Write the second introduction paragraph.',
    }),

    createField({
      field_key: 'content_block_1_title',
      field_type: 'text',
      sort_order: 21,
      label: 'Content Block 1 Title',
      section: 'Content Blocks',
      helper_text: 'First content block heading.',
      placeholder: 'What It Is',
    }),
    createField({
      field_key: 'content_block_1_text',
      field_type: 'textarea',
      sort_order: 22,
      label: 'Content Block 1 Text',
      section: 'Content Blocks',
      helper_text: 'Text for the first content block.',
      placeholder: 'Explain what the product or tool is.',
    }),
    createField({
      field_key: 'content_block_1_image',
      field_type: 'image',
      sort_order: 23,
      label: 'Content Block 1 Image',
      section: 'Content Blocks',
      helper_text: 'Optional image shown beside the first content block.',
      placeholder: 'Upload image or paste image URL',
    }),
    createField({
      field_key: 'content_block_2_title',
      field_type: 'text',
      sort_order: 24,
      label: 'Content Block 2 Title',
      section: 'Content Blocks',
      helper_text: 'Second content block heading.',
      placeholder: 'How It Works',
    }),
    createField({
      field_key: 'content_block_2_text',
      field_type: 'textarea',
      sort_order: 25,
      label: 'Content Block 2 Text',
      section: 'Content Blocks',
      helper_text: 'Text for the second content block.',
      placeholder: 'Explain how the product or tool works.',
    }),
    createField({
      field_key: 'content_block_2_image',
      field_type: 'image',
      sort_order: 26,
      label: 'Content Block 2 Image',
      section: 'Content Blocks',
      helper_text: 'Optional image shown beside the second content block.',
      placeholder: 'Upload image or paste image URL',
    }),

    createField({
      field_key: 'features_title',
      field_type: 'text',
      sort_order: 27,
      label: 'Features Section Title',
      section: 'Benefits / Key Features',
      helper_text: 'Heading for the features section.',
      placeholder: 'Benefits / Key Features',
    }),
    createField({
      field_key: 'features_intro',
      field_type: 'textarea',
      sort_order: 28,
      label: 'Features Intro',
      section: 'Benefits / Key Features',
      helper_text: 'Short intro text before the feature icons.',
      placeholder: 'ProductX comes with a wide range of features that help teams save time and get more done.',
    }),
    createField({
      field_key: 'feature_1_title',
      field_type: 'text',
      sort_order: 29,
      label: 'Feature 1 Title',
      section: 'Benefits / Key Features',
      helper_text: 'First feature title.',
      placeholder: 'Automation',
    }),
    createField({
      field_key: 'feature_1_text',
      field_type: 'textarea',
      sort_order: 30,
      label: 'Feature 1 Text',
      section: 'Benefits / Key Features',
      helper_text: 'Short description for the first feature.',
      placeholder: 'Automate repetitive tasks and workflows.',
    }),
    createField({
      field_key: 'feature_2_title',
      field_type: 'text',
      sort_order: 31,
      label: 'Feature 2 Title',
      section: 'Benefits / Key Features',
      helper_text: 'Second feature title.',
      placeholder: 'Collaboration',
    }),
    createField({
      field_key: 'feature_2_text',
      field_type: 'textarea',
      sort_order: 32,
      label: 'Feature 2 Text',
      section: 'Benefits / Key Features',
      helper_text: 'Short description for the second feature.',
      placeholder: 'Real-time collaboration across teams.',
    }),
    createField({
      field_key: 'feature_3_title',
      field_type: 'text',
      sort_order: 33,
      label: 'Feature 3 Title',
      section: 'Benefits / Key Features',
      helper_text: 'Third feature title.',
      placeholder: 'Analytics',
    }),
    createField({
      field_key: 'feature_3_text',
      field_type: 'textarea',
      sort_order: 34,
      label: 'Feature 3 Text',
      section: 'Benefits / Key Features',
      helper_text: 'Short description for the third feature.',
      placeholder: 'Powerful insights to track performance.',
    }),
    createField({
      field_key: 'feature_4_title',
      field_type: 'text',
      sort_order: 35,
      label: 'Feature 4 Title',
      section: 'Benefits / Key Features',
      helper_text: 'Fourth feature title.',
      placeholder: 'Security',
    }),
    createField({
      field_key: 'feature_4_text',
      field_type: 'textarea',
      sort_order: 36,
      label: 'Feature 4 Text',
      section: 'Benefits / Key Features',
      helper_text: 'Short description for the fourth feature.',
      placeholder: 'Enterprise-grade security and privacy.',
    }),

    createField({
      field_key: 'pros_title',
      field_type: 'text',
      sort_order: 37,
      label: 'Pros Title',
      section: 'Pros and Cons',
      helper_text: 'Heading for the pros box.',
      placeholder: 'Pros',
    }),
    createField({
      field_key: 'pros_item_1',
      field_type: 'text',
      sort_order: 38,
      label: 'Pros Item 1',
      section: 'Pros and Cons',
      helper_text: 'First pros list item.',
      placeholder: 'Easy to use and intuitive interface',
    }),
    createField({
      field_key: 'pros_item_2',
      field_type: 'text',
      sort_order: 39,
      label: 'Pros Item 2',
      section: 'Pros and Cons',
      helper_text: 'Second pros list item.',
      placeholder: 'Feature-rich and highly customizable',
    }),
    createField({
      field_key: 'pros_item_3',
      field_type: 'text',
      sort_order: 40,
      label: 'Pros Item 3',
      section: 'Pros and Cons',
      helper_text: 'Third pros list item.',
      placeholder: 'Excellent customer support',
    }),
    createField({
      field_key: 'pros_item_4',
      field_type: 'text',
      sort_order: 41,
      label: 'Pros Item 4',
      section: 'Pros and Cons',
      helper_text: 'Fourth pros list item.',
      placeholder: 'Great value for the price',
    }),
    createField({
      field_key: 'cons_title',
      field_type: 'text',
      sort_order: 42,
      label: 'Cons Title',
      section: 'Pros and Cons',
      helper_text: 'Heading for the cons box.',
      placeholder: 'Cons',
    }),
    createField({
      field_key: 'cons_item_1',
      field_type: 'text',
      sort_order: 43,
      label: 'Cons Item 1',
      section: 'Pros and Cons',
      helper_text: 'First cons list item.',
      placeholder: 'Steeper learning curve for advanced features',
    }),
    createField({
      field_key: 'cons_item_2',
      field_type: 'text',
      sort_order: 44,
      label: 'Cons Item 2',
      section: 'Pros and Cons',
      helper_text: 'Second cons list item.',
      placeholder: 'Some integrations could be improved',
    }),
    createField({
      field_key: 'cons_item_3',
      field_type: 'text',
      sort_order: 45,
      label: 'Cons Item 3',
      section: 'Pros and Cons',
      helper_text: 'Third cons list item.',
      placeholder: 'Mobile app lacks a few features',
    }),

    createField({
      field_key: 'faq_title',
      field_type: 'text',
      sort_order: 46,
      label: 'FAQ Title',
      section: 'Frequently Asked Questions',
      helper_text: 'Heading for the FAQ section.',
      placeholder: 'Frequently Asked Questions',
    }),
    createField({
      field_key: 'faq_1_question',
      field_type: 'text',
      sort_order: 47,
      label: 'FAQ 1 Question',
      section: 'Frequently Asked Questions',
      helper_text: 'First FAQ question.',
      placeholder: 'Is ProductX suitable for small teams?',
    }),
    createField({
      field_key: 'faq_1_answer',
      field_type: 'textarea',
      sort_order: 48,
      label: 'FAQ 1 Answer',
      section: 'Frequently Asked Questions',
      helper_text: 'First FAQ answer.',
      placeholder: 'Write the answer here.',
    }),
    createField({
      field_key: 'faq_2_question',
      field_type: 'text',
      sort_order: 49,
      label: 'FAQ 2 Question',
      section: 'Frequently Asked Questions',
      helper_text: 'Second FAQ question.',
      placeholder: 'Does ProductX offer a free trial?',
    }),
    createField({
      field_key: 'faq_2_answer',
      field_type: 'textarea',
      sort_order: 50,
      label: 'FAQ 2 Answer',
      section: 'Frequently Asked Questions',
      helper_text: 'Second FAQ answer.',
      placeholder: 'Write the answer here.',
    }),
    createField({
      field_key: 'faq_3_question',
      field_type: 'text',
      sort_order: 51,
      label: 'FAQ 3 Question',
      section: 'Frequently Asked Questions',
      helper_text: 'Third FAQ question.',
      placeholder: 'What integrations does ProductX support?',
    }),
    createField({
      field_key: 'faq_3_answer',
      field_type: 'textarea',
      sort_order: 52,
      label: 'FAQ 3 Answer',
      section: 'Frequently Asked Questions',
      helper_text: 'Third FAQ answer.',
      placeholder: 'Write the answer here.',
    }),
    createField({
      field_key: 'faq_4_question',
      field_type: 'text',
      sort_order: 53,
      label: 'FAQ 4 Question',
      section: 'Frequently Asked Questions',
      helper_text: 'Fourth FAQ question.',
      placeholder: 'Is my data secure with ProductX?',
    }),
    createField({
      field_key: 'faq_4_answer',
      field_type: 'textarea',
      sort_order: 54,
      label: 'FAQ 4 Answer',
      section: 'Frequently Asked Questions',
      helper_text: 'Fourth FAQ answer.',
      placeholder: 'Write the answer here.',
    }),

    createField({
      field_key: 'final_verdict_title',
      field_type: 'text',
      sort_order: 55,
      label: 'Final Verdict Title',
      section: 'Final Verdict',
      helper_text: 'Closing section heading.',
      placeholder: 'Final Verdict',
    }),
    createField({
      field_key: 'final_verdict_text',
      field_type: 'textarea',
      sort_order: 56,
      label: 'Final Verdict Text',
      section: 'Final Verdict',
      helper_text: 'Closing verdict paragraph.',
      placeholder: 'Write your final verdict here.',
    }),

    createField({
      field_key: 'email_capture_title',
      field_type: 'text',
      sort_order: 57,
      label: 'Email Capture Title',
      section: 'Email Capture Box',
      helper_text: 'Sidebar newsletter heading.',
      placeholder: 'Stay Updated',
    }),
    createField({
      field_key: 'email_capture_text',
      field_type: 'textarea',
      sort_order: 58,
      label: 'Email Capture Text',
      section: 'Email Capture Box',
      helper_text: 'Sidebar newsletter description.',
      placeholder: 'Get the latest reviews, guides, and deals straight to your inbox.',
    }),
    createField({
      field_key: 'email_capture_placeholder',
      field_type: 'text',
      sort_order: 59,
      label: 'Email Input Placeholder',
      section: 'Email Capture Box',
      helper_text: 'Placeholder text inside the email input.',
      placeholder: 'Enter your email',
    }),
    createField({
      field_key: 'email_capture_button_label',
      field_type: 'text',
      sort_order: 60,
      label: 'Subscribe Button Label',
      section: 'Email Capture Box',
      helper_text: 'Button text for the email capture box.',
      placeholder: 'Subscribe',
    }),
    createField({
      field_key: 'email_capture_privacy_text',
      field_type: 'text',
      sort_order: 61,
      label: 'Privacy Text',
      section: 'Email Capture Box',
      helper_text: 'Small privacy note under the subscribe button.',
      placeholder: 'We respect your privacy.',
    }),

    createField({
      field_key: 'related_posts_title',
      field_type: 'text',
      sort_order: 62,
      label: 'Related Posts Title',
      section: 'Related Posts',
      helper_text: 'Heading above the related posts cards.',
      placeholder: 'Related Posts',
    }),
    createField({
      field_key: 'related_post_1_title',
      field_type: 'text',
      sort_order: 63,
      label: 'Related Post 1 Title',
      section: 'Related Posts',
      helper_text: 'Title for the first manual related post card.',
      placeholder: 'Best Project Management Tools for 2024',
    }),
    createField({
      field_key: 'related_post_1_image',
      field_type: 'image',
      sort_order: 64,
      label: 'Related Post 1 Image',
      section: 'Related Posts',
      helper_text: 'Image for the first manual related post card.',
      placeholder: 'Upload image or paste image URL',
    }),
    createField({
      field_key: 'related_post_1_meta',
      field_type: 'text',
      sort_order: 65,
      label: 'Related Post 1 Meta',
      section: 'Related Posts',
      helper_text: 'Date and read time for the first manual related post card.',
      placeholder: 'May 1, 2024 · 7 min read',
    }),
    createField({
      field_key: 'related_post_1_url',
      field_type: 'url',
      sort_order: 66,
      label: 'Related Post 1 URL',
      section: 'Related Posts',
      helper_text: 'Optional link for the first manual related post card.',
      placeholder: 'https://supgad.com/your-link',
    }),
    createField({
      field_key: 'related_post_2_title',
      field_type: 'text',
      sort_order: 67,
      label: 'Related Post 2 Title',
      section: 'Related Posts',
      helper_text: 'Title for the second manual related post card.',
      placeholder: 'ProductX vs Competitor Y: Which Is Better?',
    }),
    createField({
      field_key: 'related_post_2_image',
      field_type: 'image',
      sort_order: 68,
      label: 'Related Post 2 Image',
      section: 'Related Posts',
      helper_text: 'Image for the second manual related post card.',
      placeholder: 'Upload image or paste image URL',
    }),
    createField({
      field_key: 'related_post_2_meta',
      field_type: 'text',
      sort_order: 69,
      label: 'Related Post 2 Meta',
      section: 'Related Posts',
      helper_text: 'Date and read time for the second manual related post card.',
      placeholder: 'Apr 22, 2024 · 10 min read',
    }),
    createField({
      field_key: 'related_post_2_url',
      field_type: 'url',
      sort_order: 70,
      label: 'Related Post 2 URL',
      section: 'Related Posts',
      helper_text: 'Optional link for the second manual related post card.',
      placeholder: 'https://supgad.com/your-link',
    }),
    createField({
      field_key: 'related_post_3_title',
      field_type: 'text',
      sort_order: 71,
      label: 'Related Post 3 Title',
      section: 'Related Posts',
      helper_text: 'Title for the third manual related post card.',
      placeholder: 'How to Boost Team Productivity with Automation',
    }),
    createField({
      field_key: 'related_post_3_image',
      field_type: 'image',
      sort_order: 72,
      label: 'Related Post 3 Image',
      section: 'Related Posts',
      helper_text: 'Image for the third manual related post card.',
      placeholder: 'Upload image or paste image URL',
    }),
    createField({
      field_key: 'related_post_3_meta',
      field_type: 'text',
      sort_order: 73,
      label: 'Related Post 3 Meta',
      section: 'Related Posts',
      helper_text: 'Date and read time for the third manual related post card.',
      placeholder: 'Apr 10, 2024 · 6 min read',
    }),
    createField({
      field_key: 'related_post_3_url',
      field_type: 'url',
      sort_order: 74,
      label: 'Related Post 3 URL',
      section: 'Related Posts',
      helper_text: 'Optional link for the third manual related post card.',
      placeholder: 'https://supgad.com/your-link',
    }),
  ],

  ctaButtons: [
    createButton({
      button_key: 'summary_cta',
      button_label: 'Visit Official Site',
      button_url: '',
      button_style: 'primary',
      open_in_new_tab: true,
      sort_order: 1,
      label: 'Summary CTA Button',
      helper_text: 'Button shown inside the quick summary card.',
      required: true,
      locked: true,
    }),
    createButton({
      button_key: 'final_verdict_cta',
      button_label: 'Try ProductX Now',
      button_url: '',
      button_style: 'primary',
      open_in_new_tab: true,
      sort_order: 2,
      label: 'Final Verdict CTA Button',
      helper_text: 'Button shown beside the final verdict section.',
      required: true,
      locked: true,
    }),
  ],
};

export default SimplePostsTemplatePreset;